# Generated by Django 3.2.18 on 2023-04-21 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_actor_movie_actors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie',
            new_name='movies',
        ),
    ]
